language: php

php:
    - 5.5
    # - 5.6
    # - 7.0

sudo: false

matrix:
  fast_finish: true

addons:
  hosts:
    - test.app

cache:
  - apt

services:
  - mysql

addons:
  apt:
    packages:
      - nginx
      - realpath

install:
#  - composer install
  - .travis/install-nginx.sh
  - mysql -e 'create database homestead;'

before_script:
  - curl -vsf 'http://localhost:8080/hello.php' &> /dev/stdout
  - cat /tmp/error.log

script:
  - resolveip test.app
  - ping -c 3 test.app

